name: others workflow

on: [push]

jobs:
  build_job:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: print the name
        run: echo "name ${{ github.actor }} run this branch ${{ github.event_name }} " >> GITHUB_OUTPUT

  
  if-Windows-else:
    runs-on: Windows-latest
    steps:
        - name: default env variables in git hub
          if: runner.os == 'Windows'
          run: |
            echo "The operating system on the runner is $env:RUNNER_OS."
            echo "Name of the repo is $env:GITHUB_REPOSITORY"
            echo "Run id of the repo is $env:GITHUB_RUN_ID"
            echo "Action name  of the repo is $env:GITHUB_ACTION" 
            echo "Action where its located is $env:GITHUB_ACTION_PATH"
            echo "Owner and repositiory of the action $env:GITHUB_ACTION_REPOSITORY"
            echo "Initiated the workflow by $env:GITHUB_ACTOR"  
            echo "ID of the who is Initiated the workflow  $env:GITHUB_ACTOR_ID"            
          

        


