name: others workflow

on: [push]

jobs:
  build_job:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: print the name
        run: echo "name ${{ github.actor }} run this branch ${{ github.event_name }} " >> GITHUB_OUTPUT

  
  if-Windows-else:
    runs-on: Windows-latest
    steps:
        - name: condition 1
          if: runner.os == 'Windows'
          run: echo "The operating system on the runner is $RUNNER_OS."
        - name: condition 2
          if: runner.os != 'Windows'
          run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
        


