name: others workflow

on: [push]

jobs:
  # build_job:
  #   runs-on: 'ubuntu-latest'
  #   if: ${{ github.event_name == 'push' }}
  #   steps:
  #     - name: print the name
  #       run: echo "name ${{ github.actor }} run this branch ${{ github.event_name }} " >> GITHUB_OUTPUT

  
  # if-Windows-else:
  #   runs-on: ubuntu-latest
  #   steps:
  #       # - name: default env variables in git hub
  #       #   id: env_variables
  #       #   # if: runner.os == 'Windows'
        #   run: |
        #     # echo "The operating system on the runner is $env:RUNNER_OS."
        #     # echo "Name of the repo is $env:GITHUB_REPOSITORY"
        #     # echo "Run id of the repo is $env:GITHUB_RUN_ID"
        #     # echo "Action name  of the repo is $env:GITHUB_ACTION" 
        #     # echo "Action where its located is $env:GITHUB_ACTION_PATH"
        #     # echo "Owner and repositiory of the action $env:GITHUB_ACTION_REPOSITORY"
        #     # echo "Initiated the workflow by $env:GITHUB_ACTOR"  
        #     # echo "ID of the who is Initiated the workflow  $env:GITHUB_ACTOR_ID"  
        #     # echo "WORK FLOW RUN URL $env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID "  
        #     echo "name=venkatesh" >> "$GITHUB_OUTPUT"
            
            

        # - name: printing the env variable
        #   env:
        #     name: ${{ steps.env_variables.outputs.name }}
        #   run: echo "env variable $name"  

        # - name: Set color
        #   id: color-selector
        #   run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
        # - name: Get color
        #   env:
        #     SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        #   run: echo "The selected color is $SELECTED_COLOR"
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"



          

        


