name: others workflow

on: [push]

jobs:
  build_job:
    runs-on: 'ubuntu-latest'
    env:
      my_value: ${{ github.event== 'push'}}
    steps:
      - name: print the branch name
        run: echo "Branch name ${{ env.my_value }}"



